apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gql-app
spec:
  selector:
    matchLabels:
      app: go-gql
  replicas: 1
  template:
    metadata:
      labels:
        app: go-gql
    spec:
      containers:
      - name: go-gql-app
        image: gql-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: go-gql-app-service
spec:
  type: NodePort
  selector:
    app: go-gql
  ports:
    - port: 8084
      targetPort: 8084
      #nodePort: 30011
