// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FamilyTree struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Age     string `json:"age"`
	Address string `json:"address"`
	Contact string `json:"contact"`
}

type FamilyTreeInput struct {
	Name    string `json:"name"`
	Age     string `json:"age"`
	Address string `json:"address"`
	Contact string `json:"contact"`
}
